### ISSUE TITLE
Can't build due to missing hid.hpp, don't know how to get it.

### ISSUE THREAD

**Issue by tmsrjs** [trezor/trezord#11]
Hi guys, 

I'm getting the following error when building on ubuntu 14.10:

-- Build files have been written to: /home/vagrant/dev/lib/trezor/trezord/build
[  5%] Built target hidapi
[ 84%] Built target TrezorCrypto
[ 89%] Building CXX object CMakeFiles/trezord.dir/src/main.cpp.o
/home/vagrant/dev/lib/trezor/trezord/src/main.cpp:36:19: fatal error: hid.hpp: No such file or directory
 #include "hid.hpp"
                   ^

I've looked around to see if there was any ubuntu packages providing such headers but looking at the imports it looks like it should be in this repo somewhere, I'm a bit confused about that.

I see there was a significant refactoring regarding hid recently, maybe the build script was not updated accordingly?

This is the commit that introduced the hid.hpp include in main.cpp
https://github.com/trezor/trezord/commit/1666432fe11114ed2461ff3738f90b5cc702a86d

Any thoughts?

**Comment by jpochyla** [comment]
Oops, forgot to add the file. Sorry! Included in 8ccb19c

**Comment by tmsrjs** [comment]
Thank you!
