### ISSUE TITLE
server.crt has expired, mytrezor.com does not work in Firefox

### ISSUE THREAD

**Issue by conejoninja** [trezor/trezord#16]
The server certificate of "localback" has expired https://github.com/trezor/trezord/blob/c348d634d90cef78189013b839fd44b7c8843213/src/main.cpp#L48

The connection is refused by Firefox, and probably others non-chrome browsers, without a warning. it just keep asking to install the TREZOR's bridge.

If the user access https://localback.net:21324/ and accept the certificate the issue is gone

**Comment by prusnak** [comment]
Fixed now. Thanks!
