### ISSUE TITLE
Sign PKG installer for macOS

### ISSUE THREAD

**Issue by prusnak** [trezor/trezord#20]
$title says it all.

**Comment by kristovatlas** [comment]
+1

**Comment by prusnak** [comment]
Relevant chapter in Apple documentation:

https://developer.apple.com/library/mac/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html

**Comment by cmer** [comment]
Absolutely. This needs to happen!

**Comment by prusnak** [comment]
We are phasing out this implementation of the bridge and replacing it with a new version here: trezor/trezord-go

Moved the issue here: https://github.com/trezor/trezord-go/issues/5
