### ISSUE TITLE
libmicrohttpd version

### ISSUE THREAD

**Issue by lothar-mar** [trezor/trezord#24]
Hi

I am trying to use trezord binary version 1.1.3.
However, it seems to have been built against an old version of libmicrohttpd.
Could you release a new binary version compiled against newer  versions of libmicrohttpd? 
Using archlinux if relevant....

Thanks

```
$ trezord -f
trezord: error while loading shared libraries: libmicrohttpd.so.10: cannot open shared object file: No such file or directory
$ ls /lib/libmicrohttpd.so*
-rwxr-xr-x 1 root root 100K Apr 29 11:46 /lib/libmicrohttpd.so.12.37.0
lrwxrwxrwx 1 root root   24 Apr 29 11:46 /lib/libmicrohttpd.so.12 -> libmicrohttpd.so.12.37.0
lrwxrwxrwx 1 root root   24 Apr 29 11:46 /lib/libmicrohttpd.so -> libmicrohttpd.so.12.37.0
```

**Comment by spudowiar** [comment]
@lothar-mar You can use my AUR package https://aur.archlinux.org/packages/trezord-git

**Comment by MarkusTeufelberger** [comment]
This is _still_ an issue by the way, any news?

**Comment by prusnak** [comment]
Just build from source if you are using unsupported distribution.

**Comment by lothar-mar** [comment]
Hi.
Building from the source solved it.
