### ISSUE TITLE
failed to start server

### ISSUE THREAD

**Issue by hamiltino** [trezor/trezord#26]
```
11/07/2016 18:56:51,592 INFO  [http.client] [7fcb57135780] requesting https://wallet.trezor.io/data/bridge/cert/server.key
11/07/2016 18:56:52,343 ERROR [default] [7fcb57135780] failed to start server
11/07/2016 18:56:52,343 INFO  [default] [7fcb57135780] sleeping for 10s

```

This is what i get when building trezord from source and trying to run it. Help please 

os: debian sid

**Comment by prusnak** [comment]
When you run it without parameters it will start as a daemon.

Are you sure it is not running and you are running it for the second time (which fails, because the port is already occupied ...)

**Comment by hamiltino** [comment]
turned off the trezord service from debian install. pkill trezord from the local build and tried trezord -f again and its working. Thanks.
