### ISSUE TITLE
Keys & Checksums

### ISSUE THREAD

**Issue by dxfx** [trezor/trezord#29]
Where are the keys and checksums for your distribution? I downloaded `trezor-bridge_1.2.0_amd64.deb` but I would like to verify it with keys and a checksum.

**Comment by prusnak** [comment]
http://blog.packagecloud.io/eng/2014/10/28/howto-gpg-sign-verify-deb-packages-apt-repositories/

TL;DR:

```
debsig-verify trezor-bridge_1.2.0_amd64.deb
```
or
```
dpkg-sig --verify trezor-bridge_1.2.0_amd64.deb
```

**Comment by dxfx** [comment]
I believe I need to import your build keys. Where can I locate them?
`$ dpkg-sig --verify trezor-bridge_1.2.0_amd64.deb 
Processing trezor-bridge_1.2.0_amd64.deb...
UNKNOWNSIG _gpgbuilder B9A02A3D`

**Comment by prusnak** [comment]
Try `gpg --recv-keys 86E6792FC27BFD478860C11091F3B339B9A02A3D`

**Comment by dxfx** [comment]
Imported your key, but I still get `BADSIG _gpgbuilder`

_verify key import_
```
$ gpg --fingerprint B9A02A3D
pub   4096R/B9A02A3D 2012-03-07 [expires: 2017-03-06]
      Key fingerprint = 86E6 792F C27B FD47 8860  C110 91F3 B339 B9A0 2A3D
uid                  Pavol Rusnák <stick@satoshilabs.com>
uid                  Pavol Rusnák <stick@gk2.sk>
uid                  Pavol Rusnák <prusnak@opensuse.org>
uid                  [jpeg image of size 2449]
sub   4096R/38DC1F4D 2012-03-07 [expires: 2017-03-06]
```

_attempt to verify signed package (dpkg-sig)_
```
$ dpkg-sig --verify trezor-bridge_1.2.0_amd64.deb 
Processing trezor-bridge_1.2.0_amd64.deb...
BADSIG _gpgbuilder
```

_attempt to verify signed package (debsig-verify)_
```
$ debsig-verify trezor-bridge_1.2.0_amd64.deb
debsig: Origin Signature check failed. This deb might not be signed.
```
