### ISSUE TITLE
Versioned releases or tags?

### ISSUE THREAD

**Issue by svetlemodry** [trezor/trezord#31]
Hi,
checking out the code, I was wondering if there are any plans to create releases or tags visible under the [releases](https://github.com/trezor/trezord/releases) tab.
Version bumps are already being done: https://github.com/trezor/trezord/commit/254277b8ff314678744b315c8b6107e358f7cdb9
Thanks!

**Comment by prusnak** [comment]
Added tags.

**Comment by svetlemodry** [comment]
@prusnak awesome, thanks for the quick implementation!
