### ISSUE TITLE
Building with protobuf 3.0.2 fails

### ISSUE THREAD

**Issue by svetlemodry** [trezor/trezord#32]
Hi all!
After the upgrade of the [protobuf](https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/protobuf) package on an up-to-date Arch Linux system, building the [trezor](https://aur.archlinux.org/packages/trezord-git/) daemon dies with the error bellow.

==> Extracting sources...
  -> Creating working copy of trezord git repo...
Cloning into 'trezord'...
done.
  -> Creating working copy of trezor-crypto git repo...
Cloning into 'trezor-crypto'...
done.
==> Starting prepare()...
Submodule 'vendor/trezor-crypto' (https://github.com/trezor/trezor-crypto.git) registered for path 'vendor/trezor-crypto'
Cloning into '/build/trezord-git/src/trezord/vendor/trezor-crypto'...
done.
Submodule path 'vendor/trezor-crypto': checked out '2802d97d47bcc7f614a966740d7728b16e1bdfdf'
==> Starting pkgver()...
==> Updated version: trezord-git 1.2.0.r262.490eb46-1
==> Starting build()...
-- The C compiler identification is GNU 6.2.1
-- The CXX compiler identification is GNU 6.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CURL: /usr/lib64/libcurl.so (found version "7.51.0") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'libmicrohttpd'
--   Found libmicrohttpd, version 0.9.52
-- Found libmicrohttpd: /usr/lib64/libmicrohttpd.so
CMake Warning at /usr/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106200
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:63 (find_package)

CMake Warning at /usr/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106200
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:63 (find_package)

CMake Warning at /usr/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106200
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:63 (find_package)

CMake Warning at /usr/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106200
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:63 (find_package)

CMake Warning at /usr/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106200
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:63 (find_package)

CMake Warning at /usr/share/cmake-3.6/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106200
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.6/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:63 (find_package)

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   regex
--   thread
--   system
--   unit_test_framework
--   program_options
--   chrono
-- Found Protobuf: /usr/lib64/libprotobuf.so;-lpthread (found suitable version "3.0.0", minimum required is "2.5.0") 
-- Found JSONCPP: /usr/lib64/libjsoncpp.so  
-- Checking for module 'libusb-1.0'
--   Found libusb-1.0, version 1.0.21
-- Configuring done
-- Generating done
-- Build files have been written to: /build/trezord-git/src/trezord/build
Scanning dependencies of target hidapi
Scanning dependencies of target TrezorCrypto
[  4%] Building C object vendor/hidapi/libusb/CMakeFiles/hidapi.dir/hid.c.o
[  8%] Building C object vendor/trezor-crypto/CMakeFiles/TrezorCrypto.dir/aescrypt.c.o
[ 13%] Building C object vendor/trezor-crypto/CMakeFiles/TrezorCrypto.dir/aeskey.c.o
[ 17%] Building C object vendor/trezor-crypto/CMakeFiles/TrezorCrypto.dir/aes_modes.c.o
[ 21%] Building C object vendor/trezor-crypto/CMakeFiles/TrezorCrypto.dir/aestab.c.o
[ 26%] Linking C static library libhidapi.a
[ 26%] Built target hidapi
[ 30%] Building C object vendor/trezor-crypto/CMakeFiles/TrezorCrypto.dir/base58.c.o
[ 34%] Building C object vendor/trezor-crypto/CMakeFiles/TrezorCrypto.dir/bignum.c.o
[ 39%] Building C object vendor/trezor-crypto/CMakeFiles/TrezorCrypto.dir/bip32.c.o
[ 43%] Building C object vendor/trezor-crypto/CMakeFiles/TrezorCrypto.dir/bip39.c.o
[ 47%] Building C object vendor/trezor-crypto/CMakeFiles/TrezorCrypto.dir/ecdsa.c.o
[ 52%] Building C object vendor/trezor-crypto/CMakeFiles/TrezorCrypto.dir/hmac.c.o
[ 56%] Building C object vendor/trezor-crypto/CMakeFiles/TrezorCrypto.dir/nist256p1.c.o
[ 60%] Building C object vendor/trezor-crypto/CMakeFiles/TrezorCrypto.dir/pbkdf2.c.o
[ 65%] Building C object vendor/trezor-crypto/CMakeFiles/TrezorCrypto.dir/rand.c.o
[ 69%] Building C object vendor/trezor-crypto/CMakeFiles/TrezorCrypto.dir/ripemd160.c.o
[ 73%] Building C object vendor/trezor-crypto/CMakeFiles/TrezorCrypto.dir/secp256k1.c.o
[ 78%] Building C object vendor/trezor-crypto/CMakeFiles/TrezorCrypto.dir/sha2.c.o
[ 82%] Linking C static library libTrezorCrypto.a
[ 82%] Built target TrezorCrypto
Scanning dependencies of target trezord
[ 86%] Building C object CMakeFiles/trezord.dir/src/glibc_compat.c.o
[ 95%] Building CXX object CMakeFiles/trezord.dir/src/config/config.pb.cc.o
[ 95%] Building CXX object CMakeFiles/trezord.dir/src/main.cpp.o
In file included from /build/trezord-git/src/trezord/src/config/config.pb.cc:5:0:
/build/trezord-git/src/trezord/src/config/config.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^~~~~
/build/trezord-git/src/trezord/src/config/config.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^~~~~
/build/trezord-git/src/trezord/src/config/config.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^~~~~
/build/trezord-git/src/trezord/src/config/config.pb.cc: In function 'void protobuf_AssignDesc_config_2eproto()':
/build/trezord-git/src/trezord/src/config/config.pb.cc:54:31: error: no matching function for call to 'google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*&, DeviceDescriptor*&, const int [4], int, int, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, long unsigned int)'
       sizeof(DeviceDescriptor));
                               ^
In file included from /usr/include/google/protobuf/stubs/common.h:41:0,
                 from /build/trezord-git/src/trezord/src/config/config.pb.h:9,
                 from /build/trezord-git/src/trezord/src/config/config.pb.cc:5:
/usr/include/google/protobuf/generated_message_reflection.h:574:3: note: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::internal::GeneratedMessageReflection&)
   GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
   ^
/usr/include/google/protobuf/generated_message_reflection.h:574:3: note:   candidate expects 1 argument, 9 provided
In file included from /build/trezord-git/src/trezord/src/config/config.pb.cc:14:0:
/usr/include/google/protobuf/generated_message_reflection.h:169:3: note: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*, const google::protobuf::Message*, const int*, int, int, int, const void*, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, int, int, int)
   GeneratedMessageReflection(const Descriptor* descriptor,
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/generated_message_reflection.h:169:3: note:   candidate expects 13 arguments, 9 provided
/usr/include/google/protobuf/generated_message_reflection.h:133:3: note: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*, const google::protobuf::Message*, const int*, int, int, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, int, int, int)
   GeneratedMessageReflection(const Descriptor* descriptor,
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/generated_message_reflection.h:133:3: note:   candidate expects 11 arguments, 9 provided
/build/trezord-git/src/trezord/src/config/config.pb.cc:73:28: error: no matching function for call to 'google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*&, Configuration*&, const int [5], int, int, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, long unsigned int)'
       sizeof(Configuration));
                            ^
In file included from /usr/include/google/protobuf/stubs/common.h:41:0,
                 from /build/trezord-git/src/trezord/src/config/config.pb.h:9,
                 from /build/trezord-git/src/trezord/src/config/config.pb.cc:5:
/usr/include/google/protobuf/generated_message_reflection.h:574:3: note: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::internal::GeneratedMessageReflection&)
   GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
   ^
/usr/include/google/protobuf/generated_message_reflection.h:574:3: note:   candidate expects 1 argument, 9 provided
In file included from /build/trezord-git/src/trezord/src/config/config.pb.cc:14:0:
/usr/include/google/protobuf/generated_message_reflection.h:169:3: note: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*, const google::protobuf::Message*, const int*, int, int, int, const void*, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, int, int, int)
   GeneratedMessageReflection(const Descriptor* descriptor,
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/generated_message_reflection.h:169:3: note:   candidate expects 13 arguments, 9 provided
/usr/include/google/protobuf/generated_message_reflection.h:133:3: note: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*, const google::protobuf::Message*, const int*, int, int, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, int, int, int)
   GeneratedMessageReflection(const Descriptor* descriptor,
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/generated_message_reflection.h:133:3: note:   candidate expects 11 arguments, 9 provided
make[2]: *** [CMakeFiles/trezord.dir/build.make:111: CMakeFiles/trezord.dir/src/config/config.pb.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /build/trezord-git/src/trezord/src/core.hpp:22:0,
                 from /build/trezord-git/src/trezord/src/main.cpp:38:
/build/trezord-git/src/trezord/src/config/config.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^~~~~
/build/trezord-git/src/trezord/src/config/config.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^~~~~
/build/trezord-git/src/trezord/src/config/config.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^~~~~
make[2]: *** [CMakeFiles/trezord.dir/build.make:87: CMakeFiles/trezord.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:69: CMakeFiles/trezord.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Build failed

**Comment by prusnak** [comment]
Protobuf 3 is not supported.

**Comment by saleemrashid** [comment]
I have added Protobuf 3 support https://aur.archlinux.org/packages/trezord-git/
