### ISSUE TITLE
Malicious website can consume large amounts of memory

### ISSUE THREAD

**Issue by saleemrashid** [trezor/trezord#38]
When unconfigured, `trezord` has no access control. A malicious website can abuse this to consume large amounts of memory, via the `POST /configure` endpoint.

Although this is not yet possible from JavaScript, the addition of `WritableStream` and the `fetch` API will make this a reality **very soon**.

From a Bourne-again compatible shell, the following command demonstrates the issue.

```bash
cat <(echo -n "POST /configure HTTP/1.1\nHost: localback.net:21324\nContent-Length: $((2 ** 63 - 1))\n\n") <(xxd -p /dev/urandom | tr -d '\n') | openssl s_client -connect localback.net:21324 -quiet
```

**N.B.** For some reason, I could only consume 8 GiB of RAM out of a total of 16 GiB for my machine in this way. I suspect this is to do with the handling of `Content-Length`. Nonetheless, this is still a major issue.

On a Linux system, this could cause the out-of-memory killer to kill the `trezord` process. I'm not sure what the case is with other operating systems where I forsee a system crash as a possibility.

/cc @prusnak @runn1ng

**Comment by saleemrashid** [comment]
What's the rationale for allowing configuration in this way? `trezord` already downloads TLS certificates, I don't see why downloading the configuration couldn't also be done in this way.

Short-term solution: Place upper limit on configuration buffer
Preferred solution: Download configuration at startup, make `/configure` a no-op

**Comment by prusnak** [comment]
Rationale is that even when SatoshiLabs servers disappear one can still use trezord (for example when wallet pushes their own config into the daemon).

Certificate for localback.net hosted on our servers is a different story unrelated to this rationale. :-)

**Comment by saleemrashid** [comment]
@prusnak Anyway, the configuration doesn't work either because SatoshiLabs public keys are hardcoded. Anyway, I pinged you and @runn1ng because I spoke to you two on Gitter about it.

**Comment by prusnak** [comment]
We are phasing out this implementation of the bridge and replacing it with a new version here: https://github.com/trezor/trezord-go

Try compiling and using that one. If you find issues, please report them to that repository. Thank you!
