### ISSUE TITLE
Trying to package for NixOS, getting permissions error (I think)

### ISSUE THREAD

**Issue by canndrew** [trezor/trezord#39]
If I run `trezord -f` directly I can connect to it from the trezor wallet website and everything works great. If I instead run `sudo -u trezord -- trezord -f` then it breaks. The website can still connect to the daemon but when it gets to `POST /acquire/...` the daemon returns HTTP error 500.

Why might this be happening? I want to eventually run trezord through systemd as the trezord user but I'm currently blocked on this. My normal user is in the trezord group.

**Comment by prusnak** [comment]
Don't use sudo, it has many side effects. Does the following work?

```
$ su trezord
# trezord -f
```

**Comment by canndrew** [comment]
Nope, that does the same thing :/

**Comment by canndrew** [comment]
Sample output:

```
Jan 23 18:53:36 ballzo trezord[30051]: 23/01/2017 18:53:36,172 INFO  [http.server] [7f78677fe700] <- POST /acquire/303030313a303030383a3030/null
Jan 23 18:53:36 ballzo trezord[30051]: 23/01/2017 18:53:36,173 INFO  [core.device] [7f78677fe700] opening: 0001:0008:00
```

So it's getting to the line that prints `opening: ...` but not the line that prints `acquiring session for: ...`.

**Comment by canndrew** [comment]
Ah, the error I get on the website "HID device open failed". It looks like that error is coming from inside trezord.

**Comment by prusnak** [comment]
Then it is indeed a permission issue. You need to install udev rules.

**Comment by canndrew** [comment]
Yep, I missed that part. Thanks.
