### ISSUE TITLE
trezor-bridge_1.2.1_amd64.deb not working with debian 9 (stretch)

### ISSUE THREAD

**Issue by micressor** [trezor/trezord#46]
trezor-bridge_1.2.1_amd64.deb  from [here](https://wallet.trezor.io/data/bridge/latest/index.html) depends on libmicrohttpd10 which is only in the jessie repository.

Thanks a lot for the debian 9 re-packaging.

> $ sudo dpkg -i trezor-bridge_1.2.1_amd64.deb 
Vormals nicht ausgewähltes Paket trezor-bridge wird gewählt.
(Lese Datenbank ... 205892 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von trezor-bridge_1.2.1_amd64.deb ...
Entpacken von trezor-bridge (1.2.1) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von trezor-bridge:
 trezor-bridge hängt ab von libmicrohttpd10; aber:
  Paket libmicrohttpd10 ist nicht installiert.
> dpkg: Fehler beim Bearbeiten des Paketes trezor-bridge (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Trigger für systemd (232-25+deb9u1) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 trezor-bridge

**Comment by prusnak** [comment]
We will switch to libmicrohttpd10 in October when new Ubuntu that drops dependency on libmicrohttpd10 is released. Compile from the source for the time being.

**Comment by tannercollin** [comment]
Any update on this? I still can't install it on Debian.

**Comment by jtumano** [comment]
+1 im also waiting

**Comment by prusnak** [comment]
We are working on next generation of Bridge written in Go. Install the Bridge from source if you want to use it.

**Comment by jtumano** [comment]
thanks, compiling and installing from source worked for me

**Comment by conejoninja** [comment]
> We are working on next generation of Bridge written in **Go**. Install the Bridge from source if you want to use it.

really? nice. I might be able to help

**Comment by prusnak** [comment]
@conejoninja https://github.com/jpochyla/trezord-go
