### ISSUE TITLE
MHD_start_daemon fails to start with SSL on OSX

### ISSUE THREAD

**Issue by lionello** [trezor/trezord#47]
`http_server.hpp` line 194, the call to `MHD_start_daemon` fails (returns `null`) without error message, but succeeds after removing `MHD_USE_SSL`. 

The certificate and key appear to have been downloaded without problems, so perhaps this is an issue with whatever version of openssl my system appears to have installed?

**Comment by prusnak** [comment]
Are you building from source or is it the binary distributed by us?

**Comment by lionello** [comment]
From source.

**Comment by prusnak** [comment]
We are phasing out this implementation of the bridge and replacing it with a new version here: https://github.com/trezor/trezord-go

Try compiling and using that one. If you find issues, please report them to that repository. Thank you!
