### ISSUE TITLE
Fedora 26 build fails

### ISSUE THREAD

**Issue by AloisMahdal** [trezor/trezord#48]
Sorry I have to resort to asking via GitHub.  Since trezor-bridge RPM currently cannot be installed directly, I'm trying to build trezord using build.sh. I followed README.md:

    git clone https://github.com/trezor/trezord.git
    cd trezord
    git submodule update --init

Then I tried to install all dependencies I could guess from the Debian list and continued:

    cd src/config
    wget https://raw.githubusercontent.com/trezor/trezor-common/master/protob/config.proto
    protoc -I/usr/include -I. --cpp_out=. config.proto
    cd ../..
    ./build.sh

But eventually it fails:

    -- JsonCpp Version: 1.8.0
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/amahdal/vcs.upstream/trezord/build/lib/jsoncpp
    [100%] Built target jsoncpp_lib_static
    -- Checking for module 'libmicrohttpd'
    --   Found libmicrohttpd, version 0.9.55
    -- Found libmicrohttpd: /usr/lib64/libmicrohttpd.so
    CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:771 (message):
      Imported targets not available for Boost version
    Call Stack (most recent call first):
      /usr/share/cmake/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/share/cmake/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:69 (find_package)

    CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:771 (message):
      Imported targets not available for Boost version
    Call Stack (most recent call first):
      /usr/share/cmake/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/share/cmake/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:69 (find_package)

    CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:771 (message):
      Imported targets not available for Boost version
    Call Stack (most recent call first):
      /usr/share/cmake/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/share/cmake/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:69 (find_package)

    CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:771 (message):
      Imported targets not available for Boost version
    Call Stack (most recent call first):
      /usr/share/cmake/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/share/cmake/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:69 (find_package)

    CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:771 (message):
      Imported targets not available for Boost version
    Call Stack (most recent call first):
      /usr/share/cmake/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/share/cmake/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:69 (find_package)

    CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:771 (message):
      Imported targets not available for Boost version
    Call Stack (most recent call first):
      /usr/share/cmake/Modules/FindBoost.cmake:875 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/share/cmake/Modules/FindBoost.cmake:1503 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:69 (find_package)

    CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1879 (message):
      Unable to find the requested Boost libraries.

      Unable to find the Boost header files.  Please set BOOST_ROOT to the root
      directory containing Boost or BOOST_INCLUDEDIR to the directory containing
      Boost's headers.
    Call Stack (most recent call first):
      CMakeLists.txt:69 (find_package)

    CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    Boost_INCLUDE_DIR (ADVANCED)
       used as include directory in directory /home/amahdal/vcs.upstream/trezord
       used as include directory in directory /home/amahdal/vcs.upstream/trezord
       used as include directory in directory /home/amahdal/vcs.upstream/trezord
    Protobuf_LIBRARY
        linked by target "trezord" in directory /home/amahdal/vcs.upstream/trezord

    -- Configuring incomplete, errors occurred!
    See also "/home/amahdal/vcs.upstream/trezord/build/CMakeFiles/CMakeOutput.log".
    See also "/home/amahdal/vcs.upstream/trezord/build/CMakeFiles/CMakeError.log".

(sorry for incuding the whole output; I don't understand CMakese enough to know which part is important.)

[CMakeError.log](https://github.com/trezor/trezord/files/1506899/CMakeError.log)
[CMakeOutput.log](https://github.com/trezor/trezord/files/1506900/CMakeOutput.log)

**Comment by AloisMahdal** [comment]
OK, tried to install boost-devel, and the error has changed:

    -- JsonCpp Version: 1.8.0
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/me/vcs.upstream/trezord/build/lib/jsoncpp
    [100%] Built target jsoncpp_lib_static
    -- Checking for module 'libmicrohttpd'
    --   Found libmicrohttpd, version 0.9.55
    -- Found libmicrohttpd: /usr/lib64/libmicrohttpd.so
    CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1879 (message):
      Unable to find the requested Boost libraries.

      Boost version: 1.63.0

      Boost include path: /usr/include

      Could not find the following static Boost libraries:

              boost_regex
              boost_thread
              boost_system
              boost_unit_test_framework
              boost_program_options
              boost_chrono

      Some (but not all) of the required Boost libraries were found.  You may
      need to install these additional Boost libraries.  Alternatively, set
      BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
      to the location of Boost.
    Call Stack (most recent call first):
      CMakeLists.txt:69 (find_package)


    CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    Protobuf_LIBRARY
        linked by target "trezord" in directory /home/me/vcs.upstream/trezord

    -- Configuring incomplete, errors occurred!
    See also "/home/me/vcs.upstream/trezord/build/CMakeFiles/CMakeOutput.log".
    See also "/home/me/vcs.upstream/trezord/build/CMakeFiles/CMakeError.log".

RPMs that look like could contain the boost libs already came as dependencies of boost-devel:

    boost-atomic-1.63.0-9.fc26.x86_64
    boost-chrono-1.63.0-9.fc26.x86_64
    boost-container-1.63.0-9.fc26.x86_64
    boost-context-1.63.0-9.fc26.x86_64
    boost-coroutine-1.63.0-9.fc26.x86_64
    boost-date-time-1.63.0-9.fc26.x86_64
    boost-devel-1.63.0-9.fc26.x86_64
    boost-fiber-1.63.0-9.fc26.x86_64
    boost-filesystem-1.63.0-9.fc26.x86_64
    boost-graph-1.63.0-9.fc26.x86_64
    boost-iostreams-1.63.0-9.fc26.x86_64
    boost-locale-1.63.0-9.fc26.x86_64
    boost-log-1.63.0-9.fc26.x86_64
    boost-math-1.63.0-9.fc26.x86_64
    boost-numpy-1.63.0-9.fc26.x86_64
    boost-program-options-1.63.0-9.fc26.x86_64
    boost-python-1.63.0-9.fc26.x86_64
    boost-random-1.63.0-9.fc26.x86_64
    boost-regex-1.63.0-9.fc26.x86_64
    boost-serialization-1.63.0-9.fc26.x86_64
    boost-signals-1.63.0-9.fc26.x86_64
    boost-system-1.63.0-9.fc26.x86_64
    boost-test-1.63.0-9.fc26.x86_64
    boost-thread-1.63.0-9.fc26.x86_64
    boost-timer-1.63.0-9.fc26.x86_64
    boost-type_erasure-1.63.0-9.fc26.x86_64
    boost-wave-1.63.0-9.fc26.x86_64

I tried `BOOST_LIBRARYDIR=/usr/include/boost ./build.sh` to no avail (reported Boost include path is still `/usr/include`).

**Comment by prusnak** [comment]
You need static versions of the libraries. Install `boost-devel-static` package. Feel free to reopen if that does not help.

**Comment by AloisMahdal** [comment]
Thanks, installing `boost-devel-static` got me to the next block:

    $ ./build.sh
    -- JsonCpp Version: 1.8.0
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/amahdal/vcs.upstream/trezord/build/lib/jsoncpp
    [100%] Built target jsoncpp_lib_static
    -- Checking for module 'libmicrohttpd'
    --   Found libmicrohttpd, version 0.9.55
    -- Found libmicrohttpd: /usr/lib64/libmicrohttpd.so
    -- Boost version: 1.63.0
    -- Found the following Boost libraries:
    --   regex
    --   thread
    --   system
    --   unit_test_framework
    --   program_options
    --   chrono
    --   date_time
    --   atomic
    CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    Protobuf_LIBRARY
        linked by target "trezord" in directory /home/amahdal/vcs.upstream/trezord

    -- Configuring incomplete, errors occurred!
    See also "/home/amahdal/vcs.upstream/trezord/build/CMakeFiles/CMakeOutput.log".
    See also "/home/amahdal/vcs.upstream/trezord/build/CMakeFiles/CMakeError.log".

[CMakeOutput.log](https://github.com/trezor/trezord/files/1510852/CMakeOutput.log)
[CMakeError.log](https://github.com/trezor/trezord/files/1510854/CMakeError.log)

Any ideas?

**Comment by AloisMahdal** [comment]
BTW, I'm trying to do this on a test machine in order to come up with Fedora 26 equivalent of the package list in README.md.  I'll be happy to open PR if you help me figure out the names.

**Comment by saleemrashid** [comment]
This might help https://github.com/trezor/trezord/blob/master/release/linux/Dockerfile

**Comment by AloisMahdal** [comment]
Thanks, @saleemrashid, although given my lack of knowledge about Docker/static/dynamic/building and my aim to create minimal list, it seems to open more questions than answer.  (Why are there both -static and -devel packages and also .i386? The docker build seems rather inclusive... Which of the packages I'm missing, given I just want to build trezord on x86_64?  No need to answer any of that though; I'd rather have omeone explain the CMake error to me or just tell me what is actually missing.)

**Comment by saleemrashid** [comment]
The CMake error is probably because you're missing `protobuf-static`

**Comment by prusnak** [comment]
Install `protobuf-static` and try again.

**Comment by AloisMahdal** [comment]
Nice, `protobuf-static` did it! Thanks!
