### ISSUE TITLE
Gentoo ebuild available

### ISSUE THREAD

**Issue by salfter** [trezor/trezord#49]
It took a bit to figure this one out, but I managed to build trezord on Gentoo.  Once I had that figured out, I knocked together an ebuild and a patchfile.  The patchfile includes manual-build instructions at the top:

https://gitlab.com/salfter/portage/tree/master/net-p2p/trezord

My Portage overlay is available through Layman.

**Comment by prusnak** [comment]
Could you try to push this to the main portage?

**Comment by salfter** [comment]
Just did some testing...looks like there's a bug in that the current version of wallet.trezor.io tries to contact trezord at https://localback.net:21324, but this fails with a 403 error since localback.net isn't whitelisted.  When I commented out lines 144-148 in src/http_server.hpp and recompiled, I was able to unlock my Trezor and view balances within Firefox.  (Konqueror wouldn't unlock the Trezor, but it would view accounts once I had used Chromium to unlock it.)

As for the main Portage tree, I can try that, but they sometimes complain about ebuilds that pull from VCS...would probably need to create another ebuild that pulls a release tarball instead.

**Comment by prusnak** [comment]
` but this fails with a 403 error since localback.net isn't whitelisted`

whitelisted where?

**Comment by salfter** [comment]
From README.md for this project:

Whitelisting

You cannot connect to trezord from anywhere on the internet. Your URL needs to be specifically whitelisted; whitelist is in the signed config file, that is sent during configure/ call.

Just on a whim, I tried `curl -k https://localback.net:21324/`...got 200 from trezord instead of 403.  When Firefox (or Konqueror) try to use the same URL, though, trezord returns 403 (the URL is in https://wallet.trezor.io/app.ca658622a626e9c4d8c1.js).

**Comment by salfter** [comment]
It looks like CORS requests (as from wallet.trezor.io) are being rejected before trezord even has a chance to configure itself.

**Comment by salfter** [comment]
I figured out what's going on.  I screwed up the fixes needed to go from protobuf 2.x to 3.x.  Just one line needs to be added to src/config/config.proto to get it working with protobuf 3.x; there should be no changes to other files.  Ebuild fixes are in progress.

**Comment by salfter** [comment]
...and now the ebuild is fixed.  trezord works without issue with Firefox, at least.

**Comment by prusnak** [comment]
:+1:
