### ISSUE TITLE
update package for use with libmicrohttpd12

### ISSUE THREAD

**Issue by KaihatsuOnline** [trezor/trezord#51]
Debian 9 Stretch is the stable version and comes with libmicrohttpd12.
when installing trezor bridge it asked for an old package (trezor-bridge depends on libmicrohttpd10).

Please update to use the newest package libmicrohttpd12.
https://packages.debian.org/search?keywords=libmicrohttpd

Thank you.

**Comment by mokshasoft** [comment]
I got the same error on Fedora 27:
```
$ sudo dnf install trezor-bridge-1.2.1-1.x86_64.rpm 
Last metadata expiration check: 1:00:14 ago on Tue 12 Dec 2017 07:34:14 AM CET.
Error: 
 Problem: conflicting requests
 - nothing provides libmicrohttpd.so.10()(64bit) needed by trezor-bridge-1.2.1-1.x86_64
$ ll /usr/lib64/libmicrohttpd.so*
lrwxrwxrwx. 1 root root     24 Aug  3 20:59 /usr/lib64/libmicrohttpd.so -> libmicrohttpd.so.12.43.0
lrwxrwxrwx. 1 root root     24 Aug  3 20:59 /usr/lib64/libmicrohttpd.so.12 -> libmicrohttpd.so.12.43.0
-rwxr-xr-x. 1 root root 123568 Aug  3 20:59 /usr/lib64/libmicrohttpd.so.12.43.0
```

**Comment by AloisMahdal** [comment]
@mokshasoft before it's fixed, feel free to use my [COPR build][1] (packaged as trezord).

  [1]: https://copr.fedorainfracloud.org/coprs/amahdal/trezord/

**Comment by CryptoPietje** [comment]
Same issue here with Debian Sid.
Don't know if it's feasible, but getting it in the Debian archives/repos would be awesome.

**Comment by KaihatsuOnline** [comment]
I would like to kindly remind that this issue is still an issue.
It would be nice to be able to use my Trezor on Linux without needing to install 3rd party software such as google chrome.
Thank you.

@prusnak @jpochyla

**Comment by prusnak** [comment]
Build from source if you want to use it.

We are working on a replacement for TREZOR Bridge and we will not be updating this package.

**Comment by prusnak** [comment]
We are phasing out this implementation of the bridge and replacing it with a new version here: https://github.com/trezor/trezord-go

Try compiling and using that one. If you find issues, please report them to that repository. Thank you!
