### ISSUE TITLE
localback.net certificate expired

### ISSUE THREAD

**Issue by AloisMahdal** [trezor/trezord#55]
I just re-built trezord from master (751dcb4) and updated udev rules, but wallet.trezor.io won't recognize the daemon is running.  This is presumably because SSL certificate has expired:

    $ curl -vs https://localback.net:21324/
    *   Trying 127.0.0.1...
    * TCP_NODELAY set
    * Connected to localback.net (127.0.0.1) port 21324 (#0)
    * ALPN, offering h2
    * ALPN, offering http/1.1
    * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
    * successfully set certificate verify locations:
    *   CAfile: /etc/ssl/certs/ca-certificates.crt
      CApath: /etc/ssl/certs
    * TLSv1.2 (OUT), TLS header, Certificate Status (22):
    * TLSv1.2 (OUT), TLS handshake, Client hello (1):
    * TLSv1.2 (IN), TLS handshake, Server hello (2):
    * TLSv1.2 (IN), TLS handshake, Certificate (11):
    * TLSv1.2 (OUT), TLS alert, Server hello (2):
    * SSL certificate problem: certificate has expired
    * Curl_http_done: called premature == 1
    * stopped the pause stream!
    * Closing connection 0
    * TLSv1.2 (OUT), TLS alert, Client hello (1):

I tried restarting trezord, re-plugging in the device, `udevadm trigger`, out of ideas.

My system is Debian 9.3 (stretch).

**Comment by AloisMahdal** [comment]
Firefox tells more about the cert:

> localback.net:21324 uses an invalid security certificate.
> The certificate expired on 12/09/2017 04:27 PM.
> The current time is 12/09/2017 06:07 PM.
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by AloisMahdal** [comment]
(Accessing the address with `--insecure` gives the usual JSON.)

**Comment by prusnak** [comment]
Thanks, devops mistake. Fixed deployed to server, should be OK now
