### ISSUE TITLE
localback.net can't be resolved

### ISSUE THREAD

**Issue by corv89** [trezor/trezord#56]
Had to add following entry to /etc/hosts
`127.0.0.1 localback.net`

This is on MacOS 10.13.2

Maybe someone can explain what went wrong that I had to do it manually?

**Comment by prusnak** [comment]
Probably a glitch of your DNS provider. This works for me:

```
dig @8.8.8.8 localback.net 
```

**Comment by corv89** [comment]
Yes, that's it.

Thanks!
