### ISSUE TITLE
New udev rules do not allow trezord user to access HID device

### ISSUE THREAD

**Issue by saleemrashid** [trezor/trezord#57]

**Comment by saleemrashid** [comment]
Fixed with this patch (ignore the `CMakeLists.txt` hunk) https://aur.archlinux.org/cgit/aur.git/tree/trezord.patch?h=trezord-git#n30

**Comment by prusnak** [comment]
We are phasing out this implementation of the bridge and replacing it with a new version here: https://github.com/trezor/trezord-go

If you find issues, please report them to that repository. Thank you!
