### ISSUE TITLE
Compiling on Raspberry Pi 3

### ISSUE THREAD

**Issue by dstreppa** [trezor/trezord#58]
I am trying to install trezord on a Raspberry Pi 3 (Raspbian). I experienced problems during the source compiling, here the output:

<pre>
# cd $trezord_folder
# sudo ./build.sh
- JsonCpp Version: 1.8.0

-- Configuring done

-- Generating done

-- Build files have been written to: /home/pi/Trezord/trezord/build/lib/jsoncpp

[100%] Built target jsoncpp_lib_static

-- Found libmicrohttpd: /usr/lib/arm-linux-gnueabihf/libmicrohttpd.so

-- Boost version: 1.55.0

-- Found the following Boost libraries:

--   regex

--   thread

--   system

--   unit_test_framework

--   program_options

--   chrono

--   date_time

--   atomic

-- Configuring done

-- Generating done

-- Build files have been written to: /home/pi/Trezord/trezord/build

[  8%] Built target hidapi

[ 82%] Built target TrezorCrypto

[ 86%] Building CXX object CMakeFiles/trezord.dir/src/main.cpp.o

In file included from /home/pi/Trezord/trezord/src/main.cpp:40:0:

/home/pi/Trezord/trezord/src/http_server.hpp: In static member function ‘static int trezord::http_server::server::request_callback(void*, MHD_Connection*, const char*, const char*, const char*, const char*, std::size_t*, void**)’:

/home/pi/Trezord/trezord/src/http_server.hpp:250:13: error: use of deleted function ‘std::basic_stringstream<char>::basic_stringstream(const std::basic_stringstream<char>&)’

             };

             ^

In file included from /usr/include/boost/lexical_cast.hpp:62:0,

                 from /usr/include/boost/program_options/value_semantic.hpp:14,

                 from /usr/include/boost/program_options/options_description.hpp:13,

                 from /usr/include/boost/program_options.hpp:15,

                 from /home/pi/Trezord/trezord/src/main.cpp:27:

/usr/include/c++/4.9/sstream:502:11: note: ‘std::basic_stringstream<char>::basic_stringstream(const std::basic_stringstream<char>&)’ is implicitly deleted because the default definition would be ill-formed:

     class basic_stringstream : public basic_iostream<_CharT, _Traits>

           ^

/usr/include/c++/4.9/sstream:502:11: error: use of deleted function ‘std::basic_iostream<char>::basic_iostream(const std::basic_iostream<char>&)’

In file included from /usr/include/c++/4.9/iostream:40:0,

                 from /usr/include/boost/chrono/time_point.hpp:34,

                 from /usr/include/boost/chrono/chrono.hpp:12,

                 from /home/pi/Trezord/trezord/src/main.cpp:26:

/usr/include/c++/4.9/istream:795:11: note: ‘std::basic_iostream<char>::basic_iostream(const std::basic_iostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:

     class basic_iostream
</pre>

The gcc version is  4.9.2. I realized to compile everything on an Ubuntu 16.04 machine (gcc 5.4.0).

Anyone has an idea?

**Comment by prusnak** [comment]
You need more recent version of OS. Are you using latest Raspbian available?

**Comment by dstreppa** [comment]
Hi @prusnak thank you for the response. I also think it is a problem of OS version. Indeed, currently we use Jessie (Rasbian 8), instead of the latest version Stretch (Rasbian 9).

**Comment by prusnak** [comment]
Agreed. Update to latest release of Raspbian based on Stretch and you should be OK.

**Comment by dstreppa** [comment]
Hi @prusnak, we installed a Raspian 9 (base on Strecth), but unfortunately we have a new problem during the compiling:

<pre>
pi@raspberrypi:~/Downloads/trezord $ sudo ./build.sh 
-- JsonCpp Version: 1.8.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Downloads/trezord/build/lib/jsoncpp
[100%] Built target jsoncpp_lib_static
-- Found libmicrohttpd: /usr/lib/arm-linux-gnueabihf/libmicrohttpd.so
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   regex
--   thread
--   system
--   unit_test_framework
--   program_options
--   chrono
--   date_time
--   atomic
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Downloads/trezord/build
[  8%] Built target hidapi
[ 82%] Built target TrezorCrypto
[ 86%] Linking CXX executable trezord
CMakeFiles/trezord.dir/src/glibc_compat.c.o: In function `__wrap_memcpy':
/home/pi/Downloads/trezord/src/glibc_compat.c:17: undefined reference to `memcpy@GLIBC_2.0'
CMakeFiles/trezord.dir/src/glibc_compat.c.o: In function `__wrap_secure_getenv':
/home/pi/Downloads/trezord/src/glibc_compat.c:28: undefined reference to `__secure_getenv@GLIBC_2.0'
/usr/bin/ld: trezord: No symbol version section for versioned symbol `memcpy@GLIBC_2.0'
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
CMakeFiles/trezord.dir/build.make:161: recipe for target 'trezord' failed
make[2]: *** [trezord] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/trezord.dir/all' failed
make[1]: *** [CMakeFiles/trezord.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
</pre>
