### ISSUE TITLE
Dependency is not satisfiable: libmicrohttpd10

### ISSUE THREAD

**Issue by drandreaskrueger** [trezor/trezord#60]
is `trezor-bridge_1.2.1_amd64.deb` the repo `trezord` or `trezord-go` ?

I have put the issue there: https://github.com/trezor/trezord-go/issues/10 

perhaps you simply have to [update your homepage](https://wallet.trezor.io/#/), to give the correct version for linux download, not the obsolete?

**Comment by prusnak** [comment]
Web page will be updated soon and trezord project is retired.
