### ISSUE TITLE
Utter confusion

### ISSUE THREAD

**Issue by StevenTCramer** [trezor/trezord#62]
NEM wallet say bridge is required and has link to . https://wallet.trezor.io/#/bridge

which takes you https://wallet.trezor.io/#/bridge  but also pops up your PIN window.  and then if you sign in it redirects you to your online wallet which shows nothing about the bridge.

So if you go to support and search for brdige https://doc.satoshilabs.com/trezor-user/search.html?q=Bridge

The first result is https://doc.satoshilabs.com/trezor-user/download.html?highlight=bridge

Which says download from github.  Which says Obsolete do not use.

So needless to say some confusion by the layman could occur.

**Comment by prusnak** [comment]
We will change the process soon, thanks for the report.
