### ISSUE TITLE
Build fails on Xubuntu 14.10

### ISSUE THREAD

**Issue by naleves** [trezor/trezord#7]
I've installed libjsoncpp0 and libjsoncpp-dev, but build.sh fails with:
```
-- Could NOT find JSONCPP (missing:  JSONCPP_LIBRARY) 
```
Are these not the correct libraries? I've looked for a list of dependencies for trezord but I've had no luck. build/jsoncpp/ is an empty directory.

**Comment by prusnak** [comment]
Read "Checking out sources" section of README.
