### ISSUE TITLE
Trezord takes a long time to do anything

### ISSUE THREAD

**Issue by cryptosig** [trezor/trezord#9]
I have been using the Trezor Bridge on my windows computer because the plugin refuses to work on this computer and it's the only way to get the trezor device to work on this particular computer with mytrezor.com. I have been using the electrum client with great success thus far, but there are some functions that it cannot do, such as upgrading firmware or wiping the device. I am using version 1.1.0 from the mytrezor site, and it works but everything is very slow, like it takes 5 minutes to do anything. 

Just from the initial start screen of "please plugin in the device" to actually finding the device on mytrezor.com and the trezord takes about 5 minutes. Other functions are having a similar result, such as message signing, transactions, and passphrase creation.

**Comment by prusnak** [comment]
We hope these two commits fix the issue: 152f286530d0c5736df6ef7f3f5ff5ae18214520 and 11ad983464d493800a260f2c86ab6cbb350b3cec.

We'll release bridge version 1.1.2 soon which includes these fixes.

**Comment by prusnak** [comment]
Please reopen if the issue is still not fixed.
